version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/iamge-editor # Connection string pointing to the MongoDB service
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017' # Exposing the default MongoDB port
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: